# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 10
    # Group updates to reduce noise
    groups:
      development:
        patterns:
          - "@types/*"
          - "eslint*"
          - "typescript*"
          - "@vitejs/*"
          - "vite"
          - "vitest"
          - "@vitest/*"
        update-types:
          - "minor"
          - "patch"
      production:
        patterns:
          - "react"
          - "react-dom"
          - "@tanstack/*"
          - "@radix-ui/*"
          - "@heroicons/*"
        update-types:
          - "minor"
          - "patch"
      tailwind:
        patterns:
          - "tailwind*"
          - "@tailwindcss/*"
        update-types:
          - "minor"
          - "patch"
    # Allow specific updates
    allow:
      - dependency-type: "all"
    # Add assignees to pull requests
    assignees:
      - "vimeto"
    # Add labels to pull requests
    labels:
      - "dependencies"
      - "automated"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Europe/Helsinki"
    open-pull-requests-limit: 5
    assignees:
      - "vimeto"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"