blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/vimeto/venues-app/discussions
    about: Please ask and answer questions in the discussions area
  - name: Security Issue
    url: mailto:vilhelm.toivonen@helsinki.fi
    about: Please report security vulnerabilities via email